name: newpycaret
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pycaret
      - pandas
      - streamlit
      - requests
      # Add any other pip packages you use directly
